name: test-and-publish
on:
    - push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 15.4
            - run: npm ci
            - run: npm run build
            - run: npm run format:check
            - run: npm run lint:check
            - run: npm run test
            - uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: dist
              env:
                  CI: true
    publish:
        name: publish
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 15.4
            - uses: actions/download-artifact@v2
              with:
                  name: build
                  path: dist
            - run: echo ::set-output name=CURRENT_VERSION::$(node -p "require(\"./package.json\").version")
              id: current-version

            # these steps run on all branches except master
            - name: canary version
              if: github.ref != 'refs/heads/master'
              run: npm version ${{ steps.current-version.outputs.CURRENT_VERSION }}-$GITHUB_SHA --git-tag-version false
            - name: canary publish
              if: github.ref != 'refs/heads/master'
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  tag: canary

            # these steps only run on master:
            - name: publish
              if: github.ref == 'refs/heads/master'
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
            - run: echo ::set-output name=PACKAGE::$(npm pack)
              id: package
              if: github.ref == 'refs/heads/master'
            - uses: marvinpinto/action-automatic-releases@v1.2.1
              if: github.ref == 'refs/heads/master'
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  prerelease: false
                  files: ${{ steps.package.outputs.PACKAGE }}
                  automatic_release_tag: ${{ steps.current-version.outputs.CURRENT_VERSION }}
