name: test-and-publish
on:
  - push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.4
      - run: npm ci
      - run: npm run build
      - run: npm run lint:check
      - run: npm run format:check
      - run: npm run test
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: build
          path: dist
        env:
          CI: true
  publish:
    if: github.ref == 'refs/heads/master'
    name: publish
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 15.4
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
